#!/bin/bash
# Batch error handling implementation for remaining 3 calculators
# This script documents the changes needed for Leverage, Win Rate Impact, and Sharpe Ratio

echo "REMAINING CALCULATORS - ERROR HANDLING IMPLEMENTATION PLAN"
echo "=========================================================="
echo ""
echo "1. LEVERAGE CALCULATOR (462 lines)"
echo "   Required Fixes:"
echo "   - Zero margin validation (prevent division by zero)"
echo "   - Unrealistic leverage warnings (>100x danger, >50x warning)"
echo "   - Negative value rejection for all inputs"
echo "   - Liquidation price NaN protection"
echo "   - Position value vs account balance sanity check"
echo ""
echo "2. WIN RATE IMPACT CALCULATOR (556 lines)"
echo "   Required Fixes:"
echo "   - Win rate 0-100% validation"
echo "   - Zero total trades prevention (division by zero)"
echo "   - Chart data validation before rendering"
echo "   - Extreme win rate change validation (0% to 100%)"
echo ""
echo "3. SHARPE RATIO CALCULATOR (760 lines)"
echo "   Required Fixes:"
echo "   - Standard deviation = 0 check (show 'undefined Sharpe ratio')"
echo "   - Negative Sharpe ratio explanation"
echo "   - Returns array validation (check for NaN, infinity)"
echo "   - Reasonableness checks (extreme values)"
echo ""
echo "All three calculators need standard error handling:"
echo "- showError() function"
echo "- clearError() function"  
echo "- createErrorContainer() function"
echo "- Input validation arrays"
echo "- NaN/Infinity guards on all calculations"
echo ""
echo "STATUS: Manual implementation required - patterns established in other 8 calculators"
